
all:
	echo
install:
	@echo "Making Dirs"
	mkdir -p ~/.local/etc/inteldb
	cp config.ini ~/.local/etc/inteldb/config.ini
	cp inteldb-query ~/.local/bin/inteldb-query 
	cp shortcuts/* ~/.local/bin/
	@echo "Done"

clean:
	echo ""


