#!/bin/bash
# Author: Silas Cutler
# IntelDB - Local tools

if [ $# -eq 1 ]
then
        echo -n "Notes: "
        read NOTES
        NAME=$1
else
        NAME=$2
        NOTES=$1
fi

DATE=`date +%Y%m%d`
mkdir $DATE-$NAME
cd $DATE-$NAME
log_investigation $DATE-$NAME "$NOTES" `date +%Y` `date +%m`

echo "Name: $DATE-$NAME" > .invnotes
echo "Notes: $NOTES" >> .invnotes
echo "Date: $DATE" >> .invnotes
echo "Hostname: $(hostname)" >> .invnotes


