#!/bin/bash
# Author: Silas Cutler
# IntelDB - Local tools

if [ $# -eq 1 ]
then
        echo -n "Source: "
        read SOURCE
        NAME=$1
else
        NAME=$2
        SOURCE=$1
fi

DATE=`date +%Y%m%d`
mkdir $DATE-$NAME
cd $DATE-$NAME
log_investigation $DATE-$NAME "$SOURCE" `date +%Y` `date +%m`

echo "Name: $DATE-$NAME" > .invnotes
echo "Source: $SOURCE" >> .invnotes
echo "Date: $DATE" >> .invnotes
echo "Hostname: $(hostname)" >> .invnotes


