#!/bin/bash
# Author: Silas Cutler
# IntelDB - Local tools


NAME=$1
NOTES=$2
YEAR=$3
MONTH=$4

# Not Released yet
#COMMAND='inteldb-query -a -inv $NAME -n "Notes: '$NOTES'" -z "{\"MONTH\": \"'$MONTH'\", \"YEAR\": \"'$YEAR'\"}"'
#eval $COMMAND


