#!/bin/bash

FILE=$1
NOTE=$2
MD5=`md5sum $FILE | awk '{ print $1 }'`
SHA1=`sha1sum $FILE | awk '{ print $1 }'`
SHA256=`sha256sum $FILE | awk '{ print $1 }'`

COMMAND="inteldb-query -a -f $SHA256 -n \"$NOTE\" -z '{\"md5\":\"$MD5\",\"sha1\":\"$SHA1\",\"sha256\":\"$SHA256\"}'"
eval $COMMAND


DIR=$(pwd)
COMMAND="inteldb-query -a -f $SHA256 -n \"$DIR\" "
eval $COMMAND


