#!/bin/bash

YRULE=$1

RDATE=$(date --date='30 days ago' +%s)

COMMAND='inteldb-query $2 -q -r -f "{ \"details.yara\" : { \"\$regex\": \"'$YRULE'\" , \"\$options\" : \"i\" } ,\"'added'\": { \"\$gt\": '$RDATE' }}" '
eval $COMMAND


